name: ComfyCommands
version: '${project.version}'
main: nl.daanbrocatus.comfycommands.ComfyCommands
api-version: '1.20'
commands:
  heal:
    description: Heals a player to full health.
    usage: /heal
  afk:
    description: Go AFK and become invincible. AFK players have a yellow name.
    usage: /afk
  sleep:
    description: Makes it morning and clears the weather.
    usage: /sleep
  announce:
    description: Make an announcement to everyone on the server.
    usage: /announce <message>
  savecoords:
    description: Save your current coordinates under a name.
    usage: /savecoords <name>
  listcoords:
    description: Lists all the coordinates the player has saved. You can provide a username as an argument to get someone else's list.
    usage: /listcoords <userName?>
  deletecoords:
    description: Deletes a set of coordinates.
    usage: /deletecoords <name>
  clearcoords:
    description: Clears all saved coordinates.
    usage: /clearcoords
  giveperms:
    description: Give a user permission to use a command.
    usage: /giveperms <userName> <commandName>
  listperms:
    description: Lists all permissions for the current user. You can provide a username as an argument to get someone else's permissions.
    usage: /listperms <userName?>
  revokeperms:
    description: Revokes a user's permission to use a command.
    usage: /revokeperms <userName> <commandName>
  clearperms:
    description: Clears all of a user's permissions (revokes permission for every ComfyCommands command).
    usage: /clearperms <userName>
  ec:
    description: Opens a player's enderchest.
    usage: /ec
  addgmmsg:
    description: Adds a message to the randomly selected message that is echoed after using /sleep.
    usage: /addgmmsg <message>
  removegmmsg:
    description: Removes a message from the randomly selected message that is echoed after using /sleep.
    usage: /removegmmsg <message>
  afklist:
    description: Lists all the afk players.
    usage: /afklist